apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-name-1
    application: game-server
  name: app-name-1
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    statefulset.kubernetes.io/pod-name: app-name-1