apiVersion: template.openshift.io/v1
kind: Template

labels:
  application: admin-ui

metadata:
  name: admin-ui

parameters:
  - name: APPLICATION_NAME
    value: admin-ui
    required: true
  - name: CONFIG_MAP_NAME
    value: 2021-demo-common
  - name: SECRET_NAME
    value: 2021-demo-common
  - name: REPLICAS
    value: "1"
  - name: IMAGE_REPOSITORY
    value: quay.io/uksummit2023/2023-game-admin-hq:latest
    required: true
  - name: CONTAINER_REQUEST_CPU
    value: 250m
  - name: CONTAINER_REQUEST_MEMORY
    value: 256Mi
  - name: CONTAINER_LIMIT_CPU
    value: 500m
  - name: CONTAINER_LIMIT_MEMORY
    value: 512Mi
  - name: ADMIN_USERNAME
    value: "admin"

objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${APPLICATION_NAME}
      labels:
        app.openshift.io/runtime: nodejs
        app: ${APPLICATION_NAME}
    spec:
      replicas: ${{REPLICAS}}
      selector:
        deploymentconfig: ${APPLICATION_NAME}
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APPLICATION_NAME}
            deploymentconfig: ${APPLICATION_NAME}
        spec:
          containers:
            - env:
                - name: ADMIN_USERNAME
                  value: ${ADMIN_USERNAME}
              envFrom:
                - secretRef:
                    name: ${SECRET_NAME}
                - configMapRef:
                    name: ${CONFIG_MAP_NAME}
              image: ${IMAGE_REPOSITORY}
              imagePullPolicy: Always
              name: ${APPLICATION_NAME}
              resources:
                requests:
                  cpu: ${CONTAINER_REQUEST_CPU}
                  memory: ${CONTAINER_REQUEST_MEMORY}
                limits:
                  cpu: ${CONTAINER_LIMIT_CPU}
                  memory: ${CONTAINER_LIMIT_MEMORY}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - type: ConfigChange
  
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${APPLICATION_NAME}
      labels:
        app: ${APPLICATION_NAME}
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: ${APPLICATION_NAME}

  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
    spec:
      port:
        targetPort: 8080
      to:
        kind: Service
        name: ${APPLICATION_NAME}