apiVersion: template.openshift.io/v1
kind: Template
labels:
  application: game-ui
metadata:
  name: game-ui

parameters:
  - name: APPLICATION_NAME
    value: game-ui
    required: true
  - name: ROUTE_NAME
    value: game
    required: true
  - name: REPLICAS
    value: "4"
    required: true
  - name: IMAGE_REPOSITORY
    value: quay.io/uksummit2023/2023-game-ui:latest
    required: true
  - name: CONTAINER_REQUEST_CPU
    value: 250m
  - name: CONTAINER_REQUEST_MEMORY
    value: 256Mi
  - name: CONTAINER_LIMIT_CPU
    value: 250m
  - name: CONTAINER_LIMIT_MEMORY
    value: 256Mi
  - name: ROLLOUT_STRATEGY
    value: "Rolling"
    required: true

objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app.openshift.io/runtime: nginx
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
    spec:
      replicas: ${{REPLICAS}}
      revisionHistoryLimit: 2
      selector:
        app: ${APPLICATION_NAME}
      strategy:
        type: ${ROLLOUT_STRATEGY}
      template:
        metadata:
          labels:
            app: ${APPLICATION_NAME}
        spec:
          containers:
            - image: ${IMAGE_REPOSITORY}
              imagePullPolicy: Always
              name: ${APPLICATION_NAME}
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
              resources:
                requests:
                  cpu: ${CONTAINER_REQUEST_CPU}
                  memory: ${CONTAINER_REQUEST_MEMORY}
                limits:
                  cpu: ${CONTAINER_LIMIT_CPU}
                  memory: ${CONTAINER_LIMIT_MEMORY}
      triggers:
        - type: ConfigChange

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
    spec:
      ports:
        - name: http
          port: 8080
      selector:
        app: ${APPLICATION_NAME}

  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: ${APPLICATION_NAME}
      name: game
    spec:
      port:
        targetPort: 8080
      to:
        kind: Service
        name: ${APPLICATION_NAME}