apiVersion: v1
data: null
kind: Secret
metadata:
  labels:
    application: demo-common
  name: 2021-demo-common
stringData:
  ADMIN_PASSWORD: password
  KAFKA_SVC_PASSWORD: ""
  KAFKA_SVC_USERNAME: ""