apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- patch: |-
    - op: replace
      path: /data/LOG_LEVEL
      value: info
  target:
    kind: ConfigMap
    name: 2021-demo-common
- patch: |-
    - op: replace
      path: /data/CLUSTER_NAME
      value: cluster-6dg8f.6dg8f.sandbox1683.opentlc.com
  target:
    kind: ConfigMap
    name: 2021-demo-common
- patch: |-
    - op: replace
      path: /stringData/ADMIN_PASSWORD
      value: secretsauce
  target:
    kind: Secret
    name: 2021-demo-common

resources:
- common-secret.yaml
- config-map.yaml