apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- patch: |-
    - op: replace
      path: /data/LOG_LEVEL
      value: warn
  target:
    kind: ConfigMap
    name: 2021-demo-common
- patch: |-
    - op: replace
      path: /data/CLUSTER_NAME
      value: summit-cluster
  target:
    kind: ConfigMap
    name: 2021-demo-common
- patch: |-
    - op: replace
      path: /stringData/ADMIN_PASSWORD
      value: redhat123!
  target:
    kind: Secret
    name: 2021-demo-common

resources:
- common-secret.yaml
- config-map.yaml