apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- patch: |-
    - op: replace
      path: /stringData/KAFKA_SVC_USERNAME
      value: kafka-user
  target:
    kind: Secret
    name: kafka-forwarder-secret
- patch: |-
    - op: replace
      path: /stringData/KAFKA_SVC_PASSWORD
      value: kafka-password
  target:
    kind: Secret
    name: kafka-forwarder-secret





















- patch: |-
    - op: replace
      path: /data/LOG_LEVEL
      value: warn
  target:
    kind: ConfigMap
    name: kafka-forwarder-config
- patch: |-
    - op: replace
      path: /data/KAFKA_BOOTSTRAP_URL
      value: url
  target:
    kind: ConfigMap
    name: kafka-forwarder-config
- patch: |-
    - op: replace
      path: /data/FUNCTION_LOG_LEVEL
      value: warn
  target:
    kind: ConfigMap
    name: kafka-forwarder-config
- patch: |-
    - op: replace
      path: /data/CLUSTER_NAME
      value: cluster-name
  target:
    kind: ConfigMap
    name: kafka-forwarder-config
- patch: |-
    - op: replace
      path: /data/NODE_ENV
      value: node-info
  target:
    kind: ConfigMap
    name: kafka-forwarder-config
- patch: |-
    - op: replace
      path: /spec/subscriber/uri
      value: http://event-forwarder.<cluster-name>.svc.cluster.local/
  target:
    kind: Trigger
resources:
- kafka-forwarder-secret.yaml
- kafka-forwarder-config-cm.yaml
- kafka-forwarder-attack.yaml
- kafka-forwarder-match-end.yaml
- kafka-forwarder-match-start.yaml