apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: ks-players
    app.kubernetes.io/component: ks-players
    app.kubernetes.io/instance: ks-players
  name: ks-players
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: quay.io/uksummit2023/2023-kafka-streams-player-matches-aggregator
    from:
      kind: DockerImage
      name: quay.io/uksummit2023/2023-kafka-streams-player-matches-aggregator
    generation: 2
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
