apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  labels:
    app: game-server
    application: knative-triggers
  name: app-name-scores-0
spec:
  broker: default
  filter:
    attributes:
      type: attackprocessed-app-name-0
  subscriber:
    uri: http://app-name-0.my-namespace.svc.cluster.local:8080/event/trigger
