apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  labels:
    app: game-server
    application: knative-triggers
  name: app-name-scores-1
spec:
  broker: default
  filter:
    attributes:
      type: attackprocessed-app-name-1
  subscriber:
    uri: http://app-name-1.my-namespace.svc.cluster.local:8080/event/trigger
