apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  labels:
    app: game-server
    application: knative-triggers
  name: game-server-bonuses-2
  namespace: battleships-backend
spec:
  broker: default
  filter:
    attributes:
      type: bonusprocessed-game-server-2
  subscriber:
    uri: http://game-server-2.frontend.svc.cluster.local:8080/event/trigger
