apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  labels:
    app: game-server
    application: knative-triggers
  name: game-server-bonuses-1
  namespace: battleships-backend
spec:
  broker: default
  filter:
    attributes:
      type: bonusprocessed-game-server-1
  subscriber:
    uri: http://game-server-1.frontend.svc.cluster.local:8080/event/trigger
