apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: NAMESPACE
spec:
  targetNamespaces:
  - NAMESPACE
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: datagrid
  namespace: NAMESPACE
spec:
  channel: 2.2.5
  name: infinispan
  source: community-operators
  sourceNamespace: openshift-marketplace
