apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: admin-ui
    app.openshift.io/runtime: nodejs
    application: admin-ui
  name: admin-ui
spec:
  replicas: 1
  selector:
    deploymentconfig: admin-ui
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: admin-ui
        deploymentconfig: admin-ui
    spec:
      containers:
      - env:
      - name: ADMIN_USERNAME
        value: admin
      envFrom:
      - secretRef:
          name: 2021-demo-common
      - configMapRef:
          name: 2021-demo-common
      image: quay.io/uksummit2023/2023-game-admin-hq:latest
      imagePullPolicy: Always
      name: admin-ui
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 250m
          memory: 256Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
    dnsPolicy: ClusterFirst
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
